server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: root
    password: ""
    driver-class-name: oracle.jdbc.OracleDriver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.Oracle12cDialect